spring:
  application:
    name: apirest-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/spring_boot

resources: "/Users/raullaraarranz/IdeaProjects/resources/"


eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"